title:              vudalat2000's blog
tagline:            a log of everyday life
description:        
url:                http://vudalat2000.github.io

author:
  name:             vudalat2000
  url:              https://twitter.com/na
  email:            na@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
