title:              vudalat2000's blog
tagline:            a log of daily life
description:        blog ti?ng Vi?t, vi?t b?ng Markdown. kinh nh??
url:                http://vudalat2000.github.io

author:
  name:             Vu
  url:              https://twitter.com/na
  email:            na@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           7
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
